environment:
  nodejs_version: "" # Empty means latest version

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

  # cf: https://help.appveyor.com/discussions/questions/1954-getting-version-from-packagejson
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - npm run release
  - 7z a local-note-app-win32-x64.zip local-note-app-win32-x64

artifacts:
  - path: local-note-app-win32-x64.zip
